title: Caldia Config
description: Caldia式プロパティ設定集。
author: Caldia
collections:
  index:
    permalink: "/:collection/:path/"
    output: true
    - index.md
    - install-notepadpp.md
    - install-python.md
    - install-mkdocs.md
    - install-mkdocs-material.md
    - markdown-sample.md
    - mkdocs-yml-sample.md
